# Generated by Django 4.2.7 on 2023-11-21 12:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_chains', models.CharField(max_length=50, verbose_name='Название цепи')),
                ('standard', models.CharField(choices=[('MGOST', 'M ГОСТ 588-81'), ('MISO1977', 'M ISO 1977'), ('MTISO1977', 'MT ISO 1977'), ('FVDIN', 'FV DIN'), ('FVТDIN', 'FVТ DIN'), ('FVCDIN', 'FVC DIN'), ('ZDIN', 'Z DIN'), ('ZEDIN', 'ZE DIN'), ('ZCDIN', 'ZC DIN')], max_length=13, verbose_name='Стандарт')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
                ('rate', models.FloatField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Базовая цепь',
                'verbose_name_plural': 'Базовые цепи',
            },
        ),
        migrations.CreateModel(
            name='BrandChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_brand', models.CharField(max_length=50, verbose_name='Брэнд')),
            ],
            options={
                'verbose_name': 'Брэнд цепи',
                'verbose_name_plural': 'Брэнд цепи',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('unp', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='TypeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_delivery', models.CharField(max_length=50, verbose_name='Тип доставки')),
                ('code_delivery', models.CharField(default='LS', max_length=50, verbose_name='Код доставки')),
                ('duty', models.FloatField(default=300, verbose_name='Гос. пошлина у.е.')),
            ],
            options={
                'verbose_name': 'Варианты доставки',
                'verbose_name_plural': 'Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='OtherVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_processing', models.CharField(choices=[('NOP', 'без обработки'), ('ZN', 'оцинковка(ZN)'), ('NP', 'никелирование(NP)'), ('DR', 'горячая оцинковка(DR)'), ('GM', 'покрытие цепи геомет(GM)'), ('SS', 'нержавейка(SS)')], default='NOP', max_length=30, verbose_name='Тип обработки цепи')),
                ('km_field', models.FloatField(default=1, verbose_name='Стоимость кг. дол. США')),
                ('days', models.IntegerField(default=70, verbose_name='Дней на изготовление')),
                ('margin', models.FloatField(default=1, verbose_name='Маржа')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.brandchain')),
            ],
            options={
                'verbose_name': 'Дополнительные варианты обработки',
                'verbose_name_plural': 'Дополнительные варианты обработки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0, verbose_name='Вес тон.')),
                ('rate', models.FloatField(default=0, verbose_name='Коэффициент')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('type_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.typedelivery')),
            ],
            options={
                'verbose_name': 'Стоимость доставки',
                'verbose_name_plural': 'Стоимость доставки',
            },
        ),
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.client')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес')),
                ('days', models.IntegerField(default=1, verbose_name='Дней')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата расчета')),
                ('data_delivery', models.DateField(default=datetime.datetime.now, verbose_name='Ориентировочная дата доставки')),
                ('base_chain', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.basechain')),
                ('brand', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.brandchain')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.client')),
                ('contact_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.contactclient')),
                ('type_delivery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.typedelivery')),
                ('type_processing', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.othervariant')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
            },
        ),
    ]
