# Generated by Django 4.2.7 on 2023-11-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='contact_client',
        ),
    ]
