# Generated by Django 4.2.7 on 2023-11-29 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_remove_calculation_contact_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='days',
            field=models.IntegerField(default=1, verbose_name='Дней на доставку'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес общий'),
        ),
    ]
