# Generated by Django 4.2.7 on 2023-11-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_calculation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedelivery',
            name='days',
            field=models.FloatField(default=0, verbose_name='Доставка в днях'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Дней на доставку'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Длина в метрах'),
        ),
    ]
