# Generated by Django 4.2.7 on 2023-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_typedelivery_days_alter_calculation_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedelivery',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Доставка в днях'),
        ),
    ]
