# Generated by Django 4.2.7 on 2023-11-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_alter_typedelivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='price_1m',
            field=models.FloatField(default=0, verbose_name='Стоимость метра цепи с доставкой у.е.'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='price_full',
            field=models.FloatField(default=0, verbose_name='Полная стоимость у.е.'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='quantity_chains_m',
            field=models.IntegerField(default=0, verbose_name='Количество цепи в метрах'),
        ),
    ]
