# Generated by Django 4.2.7 on 2023-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_calculation_price_1m_calculation_price_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='brand',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Общий вес'),
        ),
    ]
