# Generated by Django 4.2.7 on 2023-11-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_remove_calculation_brand_alter_calculation_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='price_1m',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Стоимость метра цепи с доставкой у.е.'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='price_full',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Полная стоимость у.е.'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Общий вес'),
        ),
        migrations.AlterField(
            model_name='othervariant',
            name='km_field',
            field=models.FloatField(default=1, verbose_name='Коэффициенты стоимости цепей'),
        ),
    ]
