# Generated by Django 4.2.7 on 2023-11-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_alter_calculation_price_1m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='price_calc_weight',
            field=models.FloatField(default=0, verbose_name='Цена из модели "Стоимость доставки"'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='price_1m',
            field=models.FloatField(default=0, verbose_name='Стоимость метра цепи с доставкой у.е.'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='price_full',
            field=models.FloatField(default=0, verbose_name='Полная стоимость у.е.'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Общий вес'),
        ),
    ]
