# Generated by Django 4.2.7 on 2023-12-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_country_remove_client_address_remove_client_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.country', verbose_name='Страна'),
        ),
    ]
