# Generated by Django 4.2.7 on 2023-12-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_alter_client_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='note',
        ),
        migrations.AlterField(
            model_name='client',
            name='entrance',
            field=models.IntegerField(default=1, verbose_name='Подъезд'),
        ),
    ]
