# Generated by Django 4.2.7 on 2023-12-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_alter_calculation_base_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='base_chain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.basechain', verbose_name='Базовая цепь'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='type_delivery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='delivery.typedelivery', verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='type_processing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.othervariant', verbose_name='Тип обработки'),
        ),
    ]
