# Generated by Django 4.2.7 on 2023-11-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fio',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='ФИО'),
        ),
    ]
